azure_openai:
  endpoint: "https://rag-cog.openai.azure.com/"
  api_version: "2024-02-15-preview"
  deployment_name: "gpt-4o-mini"  # Model deployment name
  model: "gpt-4o-mini"
  max_tokens: 4096
  temperature: 0.7

azure:
  resource_group: "generic-rag"
  subscription: "Sogeti AI Team"
